# Generated by Django 5.2.10 on 2026-02-01 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nama Produk')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('merchandise', 'Merchandise')], default='apparel', max_length=20, verbose_name='Kategori')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Judul Desain')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('image', models.URLField(max_length=500, verbose_name='Image URL')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=30, unique=True, verbose_name='SKU')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.product')),
            ],
            options={
                'verbose_name': 'Design Product',
                'verbose_name_plural': 'Design Products',
                'unique_together': {('design', 'product')},
            },
        ),
        migrations.AddField(
            model_name='design',
            name='products',
            field=models.ManyToManyField(related_name='designs', through='designs.DesignProduct', to='designs.product', verbose_name='Products'),
        ),
    ]
